steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/studysphere-repo/studysphere:$COMMIT_SHA', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/studysphere-repo/studysphere:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'studysphere'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/studysphere-repo/studysphere:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyDkqwtSG31hCKOwlMsQ0NImM-LBT8rmGCg,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=scholarsphere-kn7gn.firebaseapp.com,NEXT_PUBLIC_FIREBASE_PROJECT_ID=scholarsphere-kn7gn,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=scholarsphere-kn7gn.firebasestorage.app,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=1044590622341,NEXT_PUBLIC_FIREBASE_APP_ID=1:1044590622341:web:4956803501d6cde57b1bec'
      - '--set-secrets'
      - 'ADMIN_PASSWORD=admin-password:latest'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/studysphere-repo/studysphere:$COMMIT_SHA'